# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: roulette_development
  pool: 5
  username: postgres
  password: lolwut1412

test:
  adapter: postgresql
  encoding: unicode
  database: roulette_test
  pool: 5
  username: postgres
  password: lolwut1412
